// <auto-generated />
namespace ComputerWebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class resetpassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resetpassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201506191025212_resetpassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
