/// <autosync enabled="true" />
/// <reference path="../Content/bigshope-web/web/js/jquery.etalage.min.js" />
/// <reference path="../content/bigshope-web/web/js/jquery.flexisel.js" />
/// <reference path="../Content/bigshope-web/web/js/jquery.min.js" />
/// <reference path="../content/bigshope-web/web/js/jquery.wmuslider.js" />
/// <reference path="../content/transdmin_light/style/js/jnice.js" />
/// <reference path="../content/transdmin_light/style/js/jquery.js" />
/// <reference path="../content/transdmin_light/style/js/jquery_.js" />
/// <reference path="../rating_1_0/jquery.js" />
/// <reference path="../rating_1_0/rating.js" />
/// <reference path="bootbox.js" />
/// <reference path="bootstrap.min.js" />
/// <reference path="index.js" />
/// <reference path="jnice.js" />
/// <reference path="jquery.etalage.min.js" />
/// <reference path="jquery.flexisel.js" />
/// <reference path="jquery.rateit.js" />
/// <reference path="jquery.unobtrusive-ajax.js" />
/// <reference path="jquery.validate.min.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery.wmuslider.js" />
/// <reference path="jquery-2.2.0.js" />
/// <reference path="jquery-2.2.0.min.js" />
/// <reference path="jquerysearch/jquery-ui.js" />
/// <reference path="jquery-ui-1.11.4.custom/external/jquery/jquery.js" />
/// <reference path="jquery-ui-1.11.4.custom/jquery-ui.js" />
/// <reference path="jquery-ui-1.11.4.js" />
/// <reference path="modernizr-2.8.3.js" />
/// <reference path="rating scripts/jquery.js" />
/// <reference path="rating scripts/jquery.metadata.js" />
/// <reference path="rating scripts/jquery.rating.js" />
/// <reference path="rating.js" />
/// <reference path="respond.matchmedia.addlistener.min.js" />
/// <reference path="respond.min.js" />
/// <reference path="../validationscript/bootstrap.js" />
/// <reference path="../validationscript/formvalidation.js" />
/// <reference path="../ValidationScript/jquery.min.js" />
