//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address is required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        public static string ADDTOCART {
            get {
                return ResourceManager.GetString("ADDTOCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        public static string BillingInformation {
            get {
                return ResourceManager.GetString("BillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARD NUMBER.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City is required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string ContactUs_Comment_Your_Message {
            get {
                return ResourceManager.GetString("ContactUs_Comment_Your_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string ContactUs_Email_Tour_Email {
            get {
                return ResourceManager.GetString("ContactUs_Email_Tour_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string ContactUs_FirstName_Your_Name {
            get {
                return ResourceManager.GetString("ContactUs_FirstName_Your_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Name.
        /// </summary>
        public static string ContactUs_LastName_Your_Last_Name {
            get {
                return ResourceManager.GetString("ContactUs_LastName_Your_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country is required.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string CreateanAccount {
            get {
                return ResourceManager.GetString("CreateanAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in yBy creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.
        /// </summary>
        public static string CreatingAnAccount {
            get {
                return ResourceManager.GetString("CreatingAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Required.
        /// </summary>
        public static string CreditCardRequired {
            get {
                return ResourceManager.GetString("CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        public static string creditCards {
            get {
                return ResourceManager.GetString("creditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card number is not valid.
        /// </summary>
        public static string CreditCartInvalid {
            get {
                return ResourceManager.GetString("CreditCartInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeletePaymentCard {
            get {
                return ResourceManager.GetString("DeletePaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed By.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        public static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is empty.
        /// </summary>
        public static string emptyCart {
            get {
                return ResourceManager.GetString("emptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRATION.
        /// </summary>
        public static string EXPIRATION {
            get {
                return ResourceManager.GetString("EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRATION DATE.
        /// </summary>
        public static string EXPIRATIONDATE {
            get {
                return ResourceManager.GetString("EXPIRATIONDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All Field And Click Update.
        /// </summary>
        public static string FillAllDetails {
            get {
                return ResourceManager.GetString("FillAllDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the form below to send us a message:.
        /// </summary>
        public static string FillFormContact {
            get {
                return ResourceManager.GetString("FillFormContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAT  50% OFF.
        /// </summary>
        public static string FLAT0FF {
            get {
                return ResourceManager.GetString("FLAT0FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow US.
        /// </summary>
        public static string FollowUS {
            get {
                return ResourceManager.GetString("FollowUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR ALL PURCHASE.
        /// </summary>
        public static string FORALLPURCHASE {
            get {
                return ResourceManager.GetString("FORALLPURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET NOW.
        /// </summary>
        public static string GETNOW {
            get {
                return ResourceManager.GetString("GETNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrandTotal.
        /// </summary>
        public static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: High Low.
        /// </summary>
        public static string hightolow {
            get {
                return ResourceManager.GetString("hightolow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items In Stock.
        /// </summary>
        public static string itemsinstock {
            get {
                return ResourceManager.GetString("itemsinstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Products.
        /// </summary>
        public static string LatestProducts {
            get {
                return ResourceManager.GetString("LatestProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24x7 live.
        /// </summary>
        public static string live247 {
            get {
                return ResourceManager.GetString("live247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW CUSTOMERS.
        /// </summary>
        public static string NEWCUSTOMERS {
            get {
                return ResourceManager.GetString("NEWCUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Letter.
        /// </summary>
        public static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not numeric.
        /// </summary>
        public static string NotNumericValue {
            get {
                return ResourceManager.GetString("NotNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address.
        /// </summary>
        public static string OurAddress {
            get {
                return ResourceManager.GetString("OurAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on order over 500.
        /// </summary>
        public static string over500 {
            get {
                return ResourceManager.GetString("over500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone is required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not valid %s phone number.
        /// </summary>
        public static string PhoneNumberValidated {
            get {
                return ResourceManager.GetString("PhoneNumberValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string please {
            get {
                return ResourceManager.GetString("please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have an account with us, please log in..
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postal Code is required.
        /// </summary>
        public static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not valid %s postal code.
        /// </summary>
        public static string PostalCodeValidated {
            get {
                return ResourceManager.GetString("PostalCodeValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post By.
        /// </summary>
        public static string PostBy {
            get {
                return ResourceManager.GetString("PostBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Ordered.
        /// </summary>
        public static string ProductsOrdered {
            get {
                return ResourceManager.GetString("ProductsOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick View.
        /// </summary>
        public static string QuickView {
            get {
                return ResourceManager.GetString("QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTERED CUSTOMERS.
        /// </summary>
        public static string REGISTEREDCUSTOMERS {
            get {
                return ResourceManager.GetString("REGISTEREDCUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Security Number is required.
        /// </summary>
        public static string SecurityNumberRequired {
            get {
                return ResourceManager.GetString("SecurityNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Product.
        /// </summary>
        public static string ShareProduct {
            get {
                return ResourceManager.GetString("ShareProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star to this Product.
        /// </summary>
        public static string StartoProduct {
            get {
                return ResourceManager.GetString("StartoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State is required.
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and try submitting again.
        /// </summary>
        public static string submittingagain {
            get {
                return ResourceManager.GetString("submittingagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        public static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks For Your Ratings.
        /// </summary>
        public static string thankyouforrate {
            get {
                return ResourceManager.GetString("thankyouforrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JK Eletronics.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP BRANDS.
        /// </summary>
        public static string TOPBRANDS {
            get {
                return ResourceManager.GetString("TOPBRANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Products.
        /// </summary>
        public static string TopProducts {
            get {
                return ResourceManager.GetString("TopProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to rate.
        /// </summary>
        public static string torate {
            get {
                return ResourceManager.GetString("torate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reviews.
        /// </summary>
        public static string TotalReviews {
            get {
                return ResourceManager.GetString("TotalReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Update Customer and Payment form before submitting for checkout.
        /// </summary>
        public static string UpdateCustomerInfo {
            get {
                return ResourceManager.GetString("UpdateCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user info.
        /// </summary>
        public static string USERINFO {
            get {
                return ResourceManager.GetString("USERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Card Number.
        /// </summary>
        public static string ValidCardNo {
            get {
                return ResourceManager.GetString("ValidCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Card Number.
        /// </summary>
        public static string ValidCardNumber {
            get {
                return ResourceManager.GetString("ValidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUE.
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALL PRODUCTS.
        /// </summary>
        public static string VIEWALLPRODUCTS {
            get {
                return ResourceManager.GetString("VIEWALLPRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have Rated.
        /// </summary>
        public static string YouhaveRated {
            get {
                return ResourceManager.GetString("YouhaveRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR ACCOUNT.
        /// </summary>
        public static string YOURACCOUNT {
            get {
                return ResourceManager.GetString("YOURACCOUNT", resourceCulture);
            }
        }
    }
}
