/// <autosync enabled="true" />
/// <reference path="jquery-2.1.4.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="bootstrap.js" />
/// <reference path="respond.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery.flexisel.js" />
/// <reference path="jquery.wmuslider.js" />
/// <reference path="npm.js" />
/// <reference path="../content/bigshope-web/web/js/jquery.flexisel.js" />
/// <reference path="../content/bigshope-web/web/js/jquery.wmuslider.js" />
/// <reference path="../content/images/my jobs_files/6bad77c.js" />
/// <reference path="../content/images/my jobs_files/aec8220.js" />
/// <reference path="../content/images/my jobs_files/aquant.js" />
/// <reference path="../content/images/my jobs_files/conversion_async.js" />
/// <reference path="../content/images/my jobs_files/d6b0fdf.js" />
/// <reference path="../content/images/my jobs_files/e5341ef.js" />
/// <reference path="../content/images/my jobs_files/elogger.js" />
/// <reference path="../content/images/my jobs_files/ga.js" />
/// <reference path="../content/images/my jobs_files/gtm.js" />
/// <reference path="index.js" />
/// <reference path="jquery.unobtrusive-ajax.js" />
/// <reference path="bootbox.js" />
/// <reference path="../validationscript/bootstrap.js" />
/// <reference path="../validationscript/formvalidation.js" />
/// <reference path="../content/transdmin_light/style/js/jnice.js" />
/// <reference path="../content/transdmin_light/style/js/jquery.js" />
/// <reference path="../content/transdmin_light/style/js/jquery_.js" />
/// <reference path="jnice.js" />
/// <reference path="jquery_.js" />
/// <reference path="rating.js" />
/// <reference path="jquery.rateit.js" />
/// <reference path="jquery.etalage.js" />
/// <reference path="jquery.js" />
/// <reference path="../content/images/my jobs_files/insight.js" />
/// <reference path="../content/bigshope-web/web/js/jquery.etalage.js" />
/// <reference path="../content/bigshope-web/web/js/jquery.js" />
/// <reference path="../validationscript/jquery.js" />
